language: java
sudo: false
install:
- "./gradlew clean"
script:
- "./gradlew -S -i"
jdk:
- oraclejdk8
- openjdk7
cache:
  directories:
  - "$HOME/.gradle"
after_success: "./gradlew bintrayUpload -i -PbintrayUser=rtyler -PbintrayKey=${BINTRAY_KEY}"
env:
  global:
    secure: V9KehgjUn4c+EdAjt3ko51yzFMuyWezcjIM3rScs7WgdfeuNSGUkc4brpB2y5TrzZyoKcz/rldumrPsYGOjTgV6c8zA4Xcmoz3rJ+fWDEc9a+A+NZ/9uszy/+DU35RaIruUoyeUuV8wV8w6kCGjhghAwmZJGbZFk0Rt2LRfG2Qcd5KrY9pqV+ve1a6NDOLwSLZWGgv4u0kR3Vt9fqTwCBdqMK3IwOPJXPJN9JD2mgUKEnz1/xL9dRdylCcmQcOiUQ1dEjccfsWWF/zhUgekC6mVbQ7PcaR/aeHngYcwb7N5zDCgKQi7nPztGVLsLB8JS4f0EvGsCeeSoE1Jn4hrm4k00Z0tttQVADsLSpFZ9/razwth35Ono76znPreqv6Hweclf/+BZ6FG+hQgxzhPDktrvsUgPLy899HtfCnkdp+TCeBQoISudFBfk8kKjPPlfQOGMlFHGgaf7CL0f0R8GwTMQyO18n2Gwv4eRmikaFvFASloaFEDIZYGdXyv2YX9gUXDDlymnqJ6QOK5JDA5TLO7Jfb50/YbBMdFCkx6zz+kXb89tDPzH0hJ0MZWMmxB9VsznMszbf8CHP/+gg9i87gqkGw9ozRwotXuAZK8gdojvdNzk+qMXNq00NTtXcmbqY5tPHwGWVU1CB8rj3DmYWNugOUEWQ3C53/UblithPzo=
