language: java
sudo: false
install:
- "./gradlew clean"
script:
- "./gradlew -S -i"
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
cache:
  directories:
  - "$HOME/.gradle"
after_success: "./gradlew bintrayUpload -i -PbintrayUser=rtyler -PbintrayKey=${BINTRAY_KEY}"
bintray_key:
  secure: lGYEgJWQiA0k5ibqbUKuogyKPMZecl/3XlCYfeYr7L+eHwCUW7OALq9CHdM5IQhzLX8i+hq3/KYC/RUzl+LAihJqnF3htl5LH8wQyxH2k0bR/6i7BHEiM3gw+qczA+4ZGQ3y/eJKefKv8SZ0xxZEw8/Fzpgljo2LmZyNg+kL/xLvYeQYD+gZhDHW2p60nyUalq39Iy/Hqyw3+Q/eXRFM5sOhf8WVlfzmky4okH0UMdUMbdFKsSMOw6HwU2OtgJXO2mgAIr0IAS3To4x96aThcUI+cgT5SMEek1bsLmjKYuqI7yWFAe6IuSMh8GpDBQSMSrQtCFG8yZmf959QJhG/1B0XfmHlbJAgncp3rnrpiVjaMb+bxE6P4agy1bhbzULmb9GUbhtfQpN3zHUQFt3ov4J+03TNOnw55k/hm1hu+0i/ScTYKHq1b0ZmnXlMY0oBBymB777FnpU43PrH4Uu7thh3WaEZMKCCM7O8cHBsX0O34z/2w9JZfrc+6m30arr32p+StBpqbsdPhktOqU9Wj0nPkgOhNE+h7z9aruW9nZ9RHU1RiS+QabckTfHS4jOC313eVaIUy6vZG3Xc89yYLIpXHS/1tPrCqsGI6JqLeYOkywqxgCYemk75hiB8HsADttnrKsaKt/hWPdN1/jlyoCyzgmbxiMYiq4oVB64GMJI=
